//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет об оценке.
    /// </summary>
    // *** Start programmer edit section *** (ОтчетОбОценке CustomAttributes)

    // *** End programmer edit section *** (ОтчетОбОценке CustomAttributes)
    [AutoAltered()]
    [Caption("Отчет об оценке")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетОбОценкеE", new string[] {
            "ДатаОтчёта as \'Дата отчёта\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("ОтчетОбОценкеE", "Подробно", "ПодробноE", true, "", "Подробно", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ОтчетОбОценкеE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОтчетОбОценкеL", new string[] {
            "ДатаОтчёта as \'Дата отчёта\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ОтчетОбОценке : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаОтчёта;
        
        private IIS.Proekt.Сотрудники fСотрудники;
        
        private IIS.Proekt.DetailArrayOfПодробно fПодробно;
        
        // *** Start programmer edit section *** (ОтчетОбОценке CustomMembers)

        // *** End programmer edit section *** (ОтчетОбОценке CustomMembers)

        
        /// <summary>
        /// ДатаОтчёта.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОбОценке.ДатаОтчёта CustomAttributes)

        // *** End programmer edit section *** (ОтчетОбОценке.ДатаОтчёта CustomAttributes)
        public virtual System.DateTime ДатаОтчёта
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОбОценке.ДатаОтчёта Get start)

                // *** End programmer edit section *** (ОтчетОбОценке.ДатаОтчёта Get start)
                System.DateTime result = this.fДатаОтчёта;
                // *** Start programmer edit section *** (ОтчетОбОценке.ДатаОтчёта Get end)

                // *** End programmer edit section *** (ОтчетОбОценке.ДатаОтчёта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОбОценке.ДатаОтчёта Set start)

                // *** End programmer edit section *** (ОтчетОбОценке.ДатаОтчёта Set start)
                this.fДатаОтчёта = value;
                // *** Start programmer edit section *** (ОтчетОбОценке.ДатаОтчёта Set end)

                // *** End programmer edit section *** (ОтчетОбОценке.ДатаОтчёта Set end)
            }
        }
        
        /// <summary>
        /// Отчет об оценке.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОбОценке.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтчетОбОценке.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОбОценке.Сотрудники Get start)

                // *** End programmer edit section *** (ОтчетОбОценке.Сотрудники Get start)
                IIS.Proekt.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтчетОбОценке.Сотрудники Get end)

                // *** End programmer edit section *** (ОтчетОбОценке.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОбОценке.Сотрудники Set start)

                // *** End programmer edit section *** (ОтчетОбОценке.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтчетОбОценке.Сотрудники Set end)

                // *** End programmer edit section *** (ОтчетОбОценке.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Отчет об оценке.
        /// </summary>
        // *** Start programmer edit section *** (ОтчетОбОценке.Подробно CustomAttributes)

        // *** End programmer edit section *** (ОтчетОбОценке.Подробно CustomAttributes)
        public virtual IIS.Proekt.DetailArrayOfПодробно Подробно
        {
            get
            {
                // *** Start programmer edit section *** (ОтчетОбОценке.Подробно Get start)

                // *** End programmer edit section *** (ОтчетОбОценке.Подробно Get start)
                if ((this.fПодробно == null))
                {
                    this.fПодробно = new IIS.Proekt.DetailArrayOfПодробно(this);
                }
                IIS.Proekt.DetailArrayOfПодробно result = this.fПодробно;
                // *** Start programmer edit section *** (ОтчетОбОценке.Подробно Get end)

                // *** End programmer edit section *** (ОтчетОбОценке.Подробно Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтчетОбОценке.Подробно Set start)

                // *** End programmer edit section *** (ОтчетОбОценке.Подробно Set start)
                this.fПодробно = value;
                // *** Start programmer edit section *** (ОтчетОбОценке.Подробно Set end)

                // *** End programmer edit section *** (ОтчетОбОценке.Подробно Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетОбОценкеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОбОценкеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОбОценкеE", typeof(IIS.Proekt.ОтчетОбОценке));
                }
            }
            
            /// <summary>
            /// "ОтчетОбОценкеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетОбОценкеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетОбОценкеL", typeof(IIS.Proekt.ОтчетОбОценке));
                }
            }
        }
    }
}
