//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Оценка.
    /// </summary>
    // *** Start programmer edit section *** (Оценка CustomAttributes)

    // *** End programmer edit section *** (Оценка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОценкаE", new string[] {
            "ДатаПроведения as \'Дата проведения\'",
            "Статус as \'Статус\'",
            "Комментарии as \'Комментарии\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ОценкаE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ОценкаL", new string[] {
            "ДатаПроведения as \'Дата проведения\'",
            "Статус as \'Статус\'",
            "Комментарии as \'Комментарии\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class Оценка : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПроведения;
        
        private IIS.Proekt.Статусы fСтатус;
        
        private string fКомментарии;
        
        private IIS.Proekt.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Оценка CustomMembers)

        // *** End programmer edit section *** (Оценка CustomMembers)

        
        /// <summary>
        /// ДатаПроведения.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.ДатаПроведения CustomAttributes)

        // *** End programmer edit section *** (Оценка.ДатаПроведения CustomAttributes)
        public virtual System.DateTime ДатаПроведения
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.ДатаПроведения Get start)

                // *** End programmer edit section *** (Оценка.ДатаПроведения Get start)
                System.DateTime result = this.fДатаПроведения;
                // *** Start programmer edit section *** (Оценка.ДатаПроведения Get end)

                // *** End programmer edit section *** (Оценка.ДатаПроведения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.ДатаПроведения Set start)

                // *** End programmer edit section *** (Оценка.ДатаПроведения Set start)
                this.fДатаПроведения = value;
                // *** Start programmer edit section *** (Оценка.ДатаПроведения Set end)

                // *** End programmer edit section *** (Оценка.ДатаПроведения Set end)
            }
        }
        
        /// <summary>
        /// Комментарии.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Комментарии CustomAttributes)

        // *** End programmer edit section *** (Оценка.Комментарии CustomAttributes)
        [StrLen(255)]
        public virtual string Комментарии
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Комментарии Get start)

                // *** End programmer edit section *** (Оценка.Комментарии Get start)
                string result = this.fКомментарии;
                // *** Start programmer edit section *** (Оценка.Комментарии Get end)

                // *** End programmer edit section *** (Оценка.Комментарии Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Комментарии Set start)

                // *** End programmer edit section *** (Оценка.Комментарии Set start)
                this.fКомментарии = value;
                // *** Start programmer edit section *** (Оценка.Комментарии Set end)

                // *** End programmer edit section *** (Оценка.Комментарии Set end)
            }
        }
        
        /// <summary>
        /// Статус.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Статус CustomAttributes)

        // *** End programmer edit section *** (Оценка.Статус CustomAttributes)
        public virtual IIS.Proekt.Статусы Статус
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Статус Get start)

                // *** End programmer edit section *** (Оценка.Статус Get start)
                IIS.Proekt.Статусы result = this.fСтатус;
                // *** Start programmer edit section *** (Оценка.Статус Get end)

                // *** End programmer edit section *** (Оценка.Статус Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Статус Set start)

                // *** End programmer edit section *** (Оценка.Статус Set start)
                this.fСтатус = value;
                // *** Start programmer edit section *** (Оценка.Статус Set end)

                // *** End programmer edit section *** (Оценка.Статус Set end)
            }
        }
        
        /// <summary>
        /// Оценка.
        /// </summary>
        // *** Start programmer edit section *** (Оценка.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Оценка.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Оценка.Сотрудники Get start)

                // *** End programmer edit section *** (Оценка.Сотрудники Get start)
                IIS.Proekt.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Оценка.Сотрудники Get end)

                // *** End programmer edit section *** (Оценка.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Оценка.Сотрудники Set start)

                // *** End programmer edit section *** (Оценка.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Оценка.Сотрудники Set end)

                // *** End programmer edit section *** (Оценка.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОценкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОценкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОценкаE", typeof(IIS.Proekt.Оценка));
                }
            }
            
            /// <summary>
            /// "ОценкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОценкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОценкаL", typeof(IIS.Proekt.Оценка));
                }
            }
        }
    }
}
