//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proekt
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Подробно.
    /// </summary>
    // *** Start programmer edit section *** (Подробно CustomAttributes)

    // *** End programmer edit section *** (Подробно CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПодробноE", new string[] {
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Оценка as \'Оценка\'",
            "Оценка.Комментарии as \'Комментарии\'"}, Hidden=new string[] {
            "Сотрудники.ФИО",
            "Оценка.Комментарии"})]
    [MasterViewDefineAttribute("ПодробноE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [MasterViewDefineAttribute("ПодробноE", "Оценка", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Комментарии")]
    public class Подробно : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Proekt.Сотрудники fСотрудники;
        
        private IIS.Proekt.Оценка fОценка;
        
        private IIS.Proekt.ОтчетОбОценке fОтчетОбОценке;
        
        // *** Start programmer edit section *** (Подробно CustomMembers)

        // *** End programmer edit section *** (Подробно CustomMembers)

        
        /// <summary>
        /// Подробно.
        /// </summary>
        // *** Start programmer edit section *** (Подробно.Оценка CustomAttributes)

        // *** End programmer edit section *** (Подробно.Оценка CustomAttributes)
        [PropertyStorage(new string[] {
                "Оценка"})]
        [NotNull()]
        public virtual IIS.Proekt.Оценка Оценка
        {
            get
            {
                // *** Start programmer edit section *** (Подробно.Оценка Get start)

                // *** End programmer edit section *** (Подробно.Оценка Get start)
                IIS.Proekt.Оценка result = this.fОценка;
                // *** Start programmer edit section *** (Подробно.Оценка Get end)

                // *** End programmer edit section *** (Подробно.Оценка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Подробно.Оценка Set start)

                // *** End programmer edit section *** (Подробно.Оценка Set start)
                this.fОценка = value;
                // *** Start programmer edit section *** (Подробно.Оценка Set end)

                // *** End programmer edit section *** (Подробно.Оценка Set end)
            }
        }
        
        /// <summary>
        /// Подробно.
        /// </summary>
        // *** Start programmer edit section *** (Подробно.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Подробно.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Proekt.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Подробно.Сотрудники Get start)

                // *** End programmer edit section *** (Подробно.Сотрудники Get start)
                IIS.Proekt.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Подробно.Сотрудники Get end)

                // *** End programmer edit section *** (Подробно.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Подробно.Сотрудники Set start)

                // *** End programmer edit section *** (Подробно.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Подробно.Сотрудники Set end)

                // *** End programmer edit section *** (Подробно.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Proekt.ОтчетОбОценке.
        /// </summary>
        // *** Start programmer edit section *** (Подробно.ОтчетОбОценке CustomAttributes)

        // *** End programmer edit section *** (Подробно.ОтчетОбОценке CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ОтчетОбОценке"})]
        public virtual IIS.Proekt.ОтчетОбОценке ОтчетОбОценке
        {
            get
            {
                // *** Start programmer edit section *** (Подробно.ОтчетОбОценке Get start)

                // *** End programmer edit section *** (Подробно.ОтчетОбОценке Get start)
                IIS.Proekt.ОтчетОбОценке result = this.fОтчетОбОценке;
                // *** Start programmer edit section *** (Подробно.ОтчетОбОценке Get end)

                // *** End programmer edit section *** (Подробно.ОтчетОбОценке Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Подробно.ОтчетОбОценке Set start)

                // *** End programmer edit section *** (Подробно.ОтчетОбОценке Set start)
                this.fОтчетОбОценке = value;
                // *** Start programmer edit section *** (Подробно.ОтчетОбОценке Set end)

                // *** End programmer edit section *** (Подробно.ОтчетОбОценке Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПодробноE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПодробноE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПодробноE", typeof(IIS.Proekt.Подробно));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Подробно.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfПодробно CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfПодробно CustomAttributes)
    public class DetailArrayOfПодробно : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Proekt.DetailArrayOfПодробно members)

        // *** End programmer edit section *** (IIS.Proekt.DetailArrayOfПодробно members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Подробно by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Подробно.
        /// </summary>
        public DetailArrayOfПодробно(IIS.Proekt.ОтчетОбОценке fОтчетОбОценке) : 
                base(typeof(Подробно), ((ICSSoft.STORMNET.DataObject)(fОтчетОбОценке)))
        {
        }
        
        public IIS.Proekt.Подробно this[int index]
        {
            get
            {
                return ((IIS.Proekt.Подробно)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Proekt.Подробно dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
